### ISSUE TITLE
Crashed when creating 1.18.2 BYG colormaps

### ISSUE THREAD

**Issue by ToneyZZZ** [Sitterr/mcasaenk#1]
I'm making a colormap in this program under version universal 1.1.1, and when I add mod `oh the biomes youll go` under resource list (tried both add seperated mod resourcepack and add mod), it crashed, while many other mods works fine on same device. I've tested on another computer and it crashed again. 

Since I'm not familiar with C#, I cannot give much help on figure out which part is going wrong, but I do favor this map style and want my server has a map generated with most biomes rendered, I'll be really appreciate if any support is given.
- program version: 1.1.1
- mod: BYG 1.5.1 1.18.2 forge
with the mods curseforge page here:
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/4971536

**Comment by Sitterr** [comment]
With the newest release should work. The problem was that the mod's resource pack is not entirely correct, but the program decided to crash instead of ignoring it.
Thanks for the report

**Comment by Sitterr** [comment]
With the newest release should work. The problem was that the mod's resource pack is not entirely correct, but the program decided to crash instead of ignoring it.
Thanks for the report
